# HOW TO USE:
# The purpose of this docker-compose is to setup our application which is
# dependent on the `MongoDB` database running concurrently with this
# server for developer purposes. This configuration has hot-reloading activated.
#
# $ docker-compose -p bp8fitnesscommunity -f dev.docker-compose.yml up   #
#

version: '3.8'
services:
  db1:
    container_name: bp8fitnesscommunity_db1
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--quiet", "--logpath", "/dev/null"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "db1_data:/data/db"
      - "db1_config:/data/configdb"
    attach: false # Disable console logs here.

  db2:
    container_name: bp8fitnesscommunity_db2
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--quiet", "--logpath", "/dev/null"]
    ports:
      - 27018:27018
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "db2_data:/data/db"
      - "db2_config:/data/configdb"
    attach: false # Disable console logs here.

  db3:
    container_name: bp8fitnesscommunity_db3
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019", "--quiet", "--logpath", "/dev/null"]
    ports:
      - 27019:27019
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "db3_data:/data/db"
      - "db3_config:/data/configdb"
    attach: false # Disable console logs here.

  mongo-express:
    container_name: bp8fitnesscommunity_db_admin
    image: mongo-express:latest
    environment:
        - ME_CONFIG_MONGODB_SERVER=db1
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_URI=mongodb://db1:27017,db2:27018,db3:27019/?replicaSet=rs0
    ports:
        - '8081:8081'
    depends_on:
      - db1
      - db2
      - db3
    links:
      - db1
      - db2
      - db3
    restart: unless-stopped
    attach: false # Disable console logs here.

  # The main application.
  app:
    container_name: bp8fitnesscommunity_app
    stdin_open: true
    environment:
        BP8_BACKEND_IP: 0.0.0.0
        BP8_BACKEND_PORT: 8000
        BP8_BACKEND_HMAC_SECRET: ${BP8_BACKEND_HMAC_SECRET}
        BP8_BACKEND_HAS_DEBUGGING: ${BP8_BACKEND_HAS_DEBUGGING}
        BP8_BACKEND_IS_DEVELOPER_MODE: ${BP8_BACKEND_IS_DEVELOPER_MODE}
        BP8_BACKEND_DB_URI: mongodb://db1:27017,db2:27018,db3:27019/?replicaSet=rs0 # This is dependent on the configuration in our docker-compose file (see above).
        BP8_BACKEND_DB_NAME: ${BP8_BACKEND_DB_NAME}
        BP8_BACKEND_CACHE_URI: ${BP8_BACKEND_CACHE_URI}
        BP8_BACKEND_AWS_ACCESS_KEY: ${BP8_BACKEND_AWS_ACCESS_KEY}
        BP8_BACKEND_AWS_SECRET_KEY: ${BP8_BACKEND_AWS_SECRET_KEY}
        BP8_BACKEND_AWS_ENDPOINT: ${BP8_BACKEND_AWS_ENDPOINT}
        BP8_BACKEND_AWS_REGION: ${BP8_BACKEND_AWS_REGION}
        BP8_BACKEND_AWS_BUCKET_NAME: ${BP8_BACKEND_AWS_BUCKET_NAME}
        BP8_BACKEND_INITIAL_ROOT_ADMIN_ID: ${BP8_BACKEND_INITIAL_ROOT_ADMIN_ID}
        BP8_BACKEND_INITIAL_ROOT_ADMIN_EMAIL: ${BP8_BACKEND_INITIAL_ROOT_ADMIN_EMAIL} # Required email for root admin when project starts up
        BP8_BACKEND_INITIAL_ROOT_ADMIN_PASSWORD: ${BP8_BACKEND_INITIAL_ROOT_ADMIN_PASSWORD} # Required password for root admin when project starts up
        BP8_BACKEND_INITIAL_ORG_ID: ${BP8_BACKEND_INITIAL_ORG_ID}
        BP8_BACKEND_INITIAL_ORG_NAME: ${BP8_BACKEND_INITIAL_ORG_NAME}
        BP8_BACKEND_INITIAL_ORG_BRANCH_ID: ${BP8_BACKEND_INITIAL_ORG_BRANCH_ID}
        BP8_BACKEND_INITIAL_ORG_ADMIN_EMAIL: ${BP8_BACKEND_INITIAL_ORG_ADMIN_EMAIL}
        BP8_BACKEND_INITIAL_ORG_ADMIN_PASSWORD: ${BP8_BACKEND_INITIAL_ORG_ADMIN_PASSWORD}
        BP8_BACKEND_INITIAL_ORG_TRAINER_EMAIL: ${BP8_BACKEND_INITIAL_ORG_TRAINER_EMAIL}
        BP8_BACKEND_INITIAL_ORG_TRAINER_PASSWORD: ${BP8_BACKEND_INITIAL_ORG_TRAINER_PASSWORD}
        BP8_BACKEND_INITIAL_ORG_MEMBER_EMAIL: ${BP8_BACKEND_INITIAL_ORG_MEMBER_EMAIL}
        BP8_BACKEND_INITIAL_ORG_MEMBER_PASSWORD: ${BP8_BACKEND_INITIAL_ORG_MEMBER_PASSWORD}
        BP8_BACKEND_API_DOMAIN_NAME: ${BP8_BACKEND_API_DOMAIN_NAME}
        BP8_BACKEND_APP_DOMAIN_NAME: ${BP8_BACKEND_APP_DOMAIN_NAME}
        AWS_ACCESS_KEY: ${BP8_BACKEND_AWS_ACCESS_KEY} # AWS SDK requires this exact name.
        AWS_SECRET_KEY: ${BP8_BACKEND_AWS_SECRET_KEY} # AWS SDK requires this exact name.
        AWS_REGION: ${BP8_BACKEND_AWS_REGION}         # AWS SDK requires this exact name.
        BP8_BACKEND_PDF_BUILDER_CBFF_TEMPLATE_FILE_PATH: ${BP8_BACKEND_PDF_BUILDER_CBFF_TEMPLATE_FILE_PATH}
        BP8_BACKEND_PDF_BUILDER_DATA_DIRECTORY_PATH: ${BP8_BACKEND_PDF_BUILDER_DATA_DIRECTORY_PATH} # The directory to save our generated PDF files before we upload to S3.
        BP8_BACKEND_MAILGUN_API_KEY: ${BP8_BACKEND_MAILGUN_API_KEY}
        BP8_BACKEND_MAILGUN_DOMAIN: ${BP8_BACKEND_MAILGUN_DOMAIN}
        BP8_BACKEND_MAILGUN_API_BASE: ${BP8_BACKEND_MAILGUN_API_BASE}
        BP8_BACKEND_MAILGUN_SENDER_EMAIL: ${BP8_BACKEND_MAILGUN_SENDER_EMAIL}
        BP8_BACKEND_MAILGUN_MAINTENANCE_EMAIL: ${BP8_BACKEND_MAILGUN_MAINTENANCE_EMAIL}
        BP8_BACKEND_PAYMENT_PROCESSOR_SECRET_KEY: ${BP8_BACKEND_PAYMENT_PROCESSOR_SECRET_KEY}
        BP8_BACKEND_PAYMENT_PROCESSOR_PUBLIC_KEY: ${BP8_BACKEND_PAYMENT_PROCESSOR_PUBLIC_KEY}
        BP8_BACKEND_PAYMENT_PROCESSOR_WEBHOOK_SECRET_KEY: ${BP8_BACKEND_PAYMENT_PROCESSOR_WEBHOOK_SECRET_KEY}
        BP8_BACKEND_OPENAI_API_KEY: ${BP8_BACKEND_OPENAI_API_KEY}
        BP8_BACKEND_OPENAI_ORGANIZATION_KEY: ${BP8_BACKEND_OPENAI_ORGANIZATION_KEY}
        BP8_BACKEND_FITBIT_APP_CLIENT_ID: ${BP8_BACKEND_FITBIT_APP_CLIENT_ID}
        BP8_BACKEND_FITBIT_APP_CLIENT_SECRET: ${BP8_BACKEND_FITBIT_APP_CLIENT_SECRET}
        BP8_BACKEND_FITBIT_APP_SUBSCRIBER_VERIFICATION_CODE: ${BP8_BACKEND_FITBIT_APP_SUBSCRIBER_VERIFICATION_CODE}
        BP8_BACKEND_FITBIT_APP_REGISTRATION_SUCCESS_REDIRECT_URL: ${BP8_BACKEND_FITBIT_APP_REGISTRATION_SUCCESS_REDIRECT_URL}
        BP8_BACKEND_APP_ENABLE_2FA_ON_REGISTRATION: ${BP8_BACKEND_APP_ENABLE_2FA_ON_REGISTRATION}
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db1
      - db2
      - db3
    links:
      - db1
      - db2
      - db3
    volumes: # Connect the local filesystem with the docker filesystem. DO NOT REMOVE.
      - ./:/go/src/github.com/bci-innovation-labs/bp8fitnesscommunity-backend # IMPORTANT: Required for hotreload via `CompileDaemon`.
      - app_data:/data

  # The purpose of this is to load up and connect with Stripe (developer mode)
  # so the webhooks will be connected to your localhost computer. This means when
  # make webhook callback to our localhost server, it will correctly point to
  # the correct API endpoint we use and auto-authenticate so you don't need to
  # log in.
  stripe-cli:
    image: stripe/stripe-cli
    container_name: bp8fitnesscommunity_stripe_cli
    command: "listen --api-key ${BP8_BACKEND_PAYMENT_PROCESSOR_SECRET_KEY} --forward-to app:8000/api/v1/public/stripe-webhook"
    environment:
      BP8_BACKEND_PAYMENT_PROCESSOR_SECRET_KEY: ${BP8_BACKEND_PAYMENT_PROCESSOR_SECRET_KEY}
    depends_on:
      - app
    links:
      - app

volumes:
    app_data:
    db1_data:
    db2_data:
    db3_data:
    db1_config:
    db2_config:
    db3_config:
